const REQUEST_TEST_INFO: string = "REQUEST_TEST_INFO";
const RECEIVE_TEST_INFO: string = "RECEIVE_TEST_INFO";
const START_REQUESTING: string = "START_REQUESTING";
const ANOTHER_ACTION: string = "ANOTHER_ACTION";
const FETCH_BTC_INFO: string = "FETCH_BTC_INFO";
const LEAVE_PAGE: string = "LEAVE_PAGE";

export default {
  REQUEST_TEST_INFO,
  RECEIVE_TEST_INFO,
  START_REQUESTING,
  ANOTHER_ACTION,
  FETCH_BTC_INFO,
  LEAVE_PAGE
};
